import {useMemo,useState} from 'react';
import {BookOpen,Brain,CheckCircle2,ClipboardCheck,LayoutDashboard,Target,Trophy,Users} from 'lucide-react';

const modules=[
 {name:'Legislação e normas HU Brasil',topics:['Norma SEI nº 2/2022/DGP-EBSERH','Norma SEI nº 5/2025/DGP-EBSERH','POP.DGP.084 — seleção e nomeação de chefias','Administração Pública aplicada à HU Brasil']},
 {name:'Orçamento e Finanças Públicas',topics:['PPA, LDO e LOA','Créditos orçamentários','Empenho, liquidação e pagamento','Restos a Pagar','Execução orçamentária e financeira','Conformidade e controles']},
 {name:'Rotina técnica do SGOF',topics:['SIAFI e Tesouro Gerencial','Disponibilidade orçamentária','Nota de Empenho','Liquidação e pagamento','Retenções tributárias','Suprimento, GRU e regularidade fiscal']},
 {name:'Gestão e Liderança',topics:['Gestão de pessoas','Negociação e conflitos','Tomada de decisão','Resiliência e flexibilidade','Articulação entre áreas','Comunicação e síntese']},
 {name:'HU Brasil — Estratégia',topics:['Propósito e visão','Valores','Direcionadores','Objetivos estratégicos','Governança e visão sistêmica']}
];
const studyLessons={
'Empenho, liquidação e pagamento':{ess:['Empenho é o primeiro estágio da despesa e reserva o crédito para a obrigação.','Liquidação verifica o direito do credor com base no objeto entregue, documentos e ateste.','Pagamento vem após a regular liquidação.'],daily:'Nota fiscal urgente chega sem ateste. O risco é transformar urgência assistencial em atalho de controle.',chief:'Identifique a pendência, articule a regularização com a área competente, registre e acompanhe. Preserve conformidade e continuidade do serviço.',ask:'Como conciliar urgência hospitalar e conformidade na liquidação?',trap:'Responder apenas “não pago”. Chefia também precisa destravar a solução regular.',memo:['Empenho = compromisso','Liquidação = direito do credor','Pagamento = após liquidação']},
'SIAFI e Tesouro Gerencial':{ess:['SIAFI registra, acompanha e controla a execução orçamentária, financeira, patrimonial e contábil federal.','Tesouro Gerencial apoia consultas e análises a partir de dados do SIAFI e outros sistemas.','Chefia deve converter registros em informação para decisão.'],daily:'A gestão pergunta por que uma ação está executando abaixo do planejado.',chief:'Valide dados, compare planejamento e execução, localize gargalos e apresente causa, impacto e plano de ação.',ask:'Como os sistemas corporativos apoiam sua tomada de decisão como chefe?',trap:'Descrever apenas telas e comandos, sem mostrar análise gerencial.',memo:['SIAFI = registro/controle','TG = consulta/análise','Dado → diagnóstico → decisão']},
'Conformidade e controles':{ess:['Controle preventivo reduz retrabalho e risco.','Rastreabilidade, evidência documental e segregação fortalecem a execução.','Conformidade deve apoiar a entrega regular, não ser apenas barreira final.'],daily:'Processo incompleto chega perto do prazo final e a área solicita prioridade.',chief:'Aponte a pendência, avalie risco, articule correção, defina prazo e depois trate a causa recorrente com orientação/checklist.',ask:'Como garantir conformidade sem transformar o SGOF em gargalo?',trap:'Confundir eficiência com flexibilização de requisito obrigatório.',memo:['Prevenir','Documentar','Segregar','Gerir risco']},
'Gestão de pessoas':{ess:['Objetivos institucionais precisam virar entregas claras da equipe.','Delegar exige responsabilidade definida e acompanhamento.','Conhecimento crítico deve ser compartilhado para reduzir dependência de uma única pessoa.'],daily:'Uma rotina essencial depende de apenas um empregado e as férias dele se aproximam.',chief:'Mapeie a rotina, documente, faça treinamento cruzado e acompanhe a autonomia dos demais.',ask:'Como organizaria e desenvolveria a equipe do SGOF?',trap:'Confundir liderança com centralização ou mera cobrança.',memo:['Clareza','Delegação','Feedback','Desenvolvimento']},
'Negociação e conflitos':{ess:['Conflito técnico deve ser tratado com foco no problema.','Fatos, competências, normas e impacto institucional orientam a decisão.','Articulação não elimina a responsabilidade de decidir.'],daily:'Contabilidade e SGOF divergem sobre o tratamento de uma despesa e o processo para.',chief:'Ouça, delimite a divergência, consulte a base normativa, decida de forma fundamentada, registre e alinhe procedimento futuro.',ask:'Como agiria diante de conflito técnico entre duas áreas?',trap:'Dizer somente que buscaria consenso; às vezes a chefia precisa decidir.',memo:['Ouvir','Fundamentar','Decidir','Registrar']},
'Tomada de decisão':{ess:['Decisão gerencial combina informação, risco e tempestividade.','Nem sempre haverá 100% das informações.','Decisões relevantes devem ser fundamentadas, comunicadas e monitoradas.'],daily:'No fechamento do exercício surgem várias demandas urgentes com equipe e tempo limitados.',chief:'Priorize por prazo, risco, impacto assistencial e obrigação normativa; distribua tarefas e monitore pontos críticos.',ask:'Como decide sob pressão e com informação incompleta?',trap:'Afirmar que só decide quando tiver todas as informações.',memo:['Informação','Risco','Prioridade','Ação']},
'Administração Pública aplicada à HU Brasil':{ess:['A atuação administrativa combina legalidade, impessoalidade, moralidade, publicidade e eficiência.','Resultado deve permanecer compatível com interesse público e conformidade.','Competência, motivação e controles importam na decisão.'],daily:'Uma solução parece operacionalmente conveniente, mas o processo não está regularmente instruído.',chief:'Explique o impedimento, indique o caminho regular, articule a correção e acompanhe a solução.',ask:'Como equilibrar eficiência e legalidade na gestão financeira?',trap:'Usar eficiência como justificativa para afastar controle obrigatório.',memo:['Interesse público','Legalidade + eficiência','Competência','Controle']},
'Propósito e visão':{ess:['A estratégia 2024–2028 conecta identidade, governança, operação e resultados.','O mapa é estruturado em cinco pilares e 24 objetivos estratégicos.','O SGOF deve ligar sua execução à sustentabilidade financeira e ao resultado institucional.'],daily:'Ao justificar uma melhoria de processo do SGOF, você precisa mostrar por que ela importa além do setor.',chief:'Conecte eficiência financeira e controles à capacidade do hospital de sustentar assistência, ensino, pesquisa e inovação.',ask:'Como o SGOF contribui para a estratégia da HU Brasil?',trap:'Responder como se SGOF fosse apenas área pagadora.',memo:['Estratégia → operação','5 pilares','24 objetivos','Sustentabilidade financeira']}
};

Object.assign(studyLessons,{
'PPA, LDO e LOA':{ess:['PPA orienta objetivos e programas de médio prazo.','LDO conecta planejamento e orçamento anual, fixando prioridades e diretrizes.','LOA estima receitas e fixa despesas do exercício.'],daily:'Uma demanda necessária ao hospital surge, mas não há dotação suficiente na programação atual.',chief:'Verifique planejamento, classificação e disponibilidade; não trate necessidade como autorização automática para gastar; articule solução orçamentária regular.',ask:'Como PPA, LDO e LOA se relacionam com a execução do SGOF?',trap:'Dizer que LOA é apenas previsão financeira; ela também fixa despesas.',memo:['PPA = direção','LDO = ponte','LOA = orçamento anual']},
'Créditos orçamentários':{ess:['Crédito orçamentário é autorização para realizar despesa.','Créditos adicionais ajustam o orçamento quando a dotação é insuficiente, inexistente ou há situação extraordinária, conforme a espécie.','Crédito não é o mesmo que recurso financeiro.'],daily:'Há orçamento aprovado para uma compra, mas o setor confunde saldo de dotação com dinheiro disponível para pagamento.',chief:'Separe execução orçamentária da financeira e confirme crédito, fonte e programação antes de orientar a continuidade.',ask:'Qual a diferença entre crédito e recurso?',trap:'Usar os termos como sinônimos.',memo:['Crédito = autorização','Recurso = disponibilidade financeira','Suplementar/especial/extraordinário']},
'Restos a Pagar':{ess:['RAP são despesas empenhadas e não pagas até 31 de dezembro.','Processados: já liquidados; não processados: ainda não liquidados.','A inscrição e gestão de RAP exigem análise do estágio e da obrigação.'],daily:'No fechamento do exercício há empenhos com objetos ainda não entregues e outros já atestados, mas sem pagamento.',chief:'Classifique corretamente, verifique condições de inscrição/manutenção e acompanhe saldos para evitar estoque sem justificativa.',ask:'Explique RAP processado e não processado e o risco gerencial de cada um.',trap:'Dizer que todo RAP é dívida já liquidada.',memo:['Empenhado + não pago = RAP','Processado = liquidado','Não processado = não liquidado']},
'Execução orçamentária e financeira':{ess:['Execução orçamentária utiliza créditos autorizados.','Execução financeira movimenta recursos para honrar obrigações.','Boa gestão sincroniza contratação, empenho, liquidação, programação e pagamento.'],daily:'O setor possui saldo orçamentário, mas enfrenta limitação financeira para pagamentos.',chief:'Diagnostique separadamente crédito e recurso, priorize obrigações e articule programação financeira.',ask:'Pode existir orçamento sem disponibilidade financeira imediata?',trap:'Confundir dotação com saldo bancário.',memo:['Orçamentária = crédito','Financeira = recurso','Sincronizar fluxos']},
'Disponibilidade orçamentária':{ess:['Antes de assumir obrigação é necessário verificar suporte orçamentário adequado.','A análise envolve saldo, classificação e compatibilidade da despesa.','A disponibilidade não substitui as demais etapas da contratação e execução.'],daily:'Área solicita contratação urgente e quer iniciar o processo antes de confirmar suporte orçamentário.',chief:'Verifique enquadramento e saldo, documente a informação e sinalize riscos antes da assunção da obrigação.',ask:'Qual o papel da disponibilidade orçamentária no controle preventivo?',trap:'Tratá-la como autorização final da despesa.',memo:['Antes da obrigação','Saldo + classificação','Controle preventivo']},
'Nota de Empenho':{ess:['A Nota de Empenho materializa o registro do empenho.','Deve refletir corretamente credor, objeto, classificação e valor.','Erros no empenho repercutem nas etapas seguintes.'],daily:'O processo chega para liquidação e a descrição/elemento do empenho não corresponde ao objeto recebido.',chief:'Não empurre o erro para a fase seguinte; valide a origem, providencie regularização cabível e registre a correção.',ask:'Por que a qualidade do empenho impacta a liquidação?',trap:'Achar que qualquer erro pode ser corrigido apenas no pagamento.',memo:['Empenho correto evita retrabalho','Objeto/classificação/valor','Regularizar na origem']},
'Liquidação e pagamento':{ess:['Liquidação verifica objeto, origem, importância e credor da obrigação.','Ateste e documentação sustentam o reconhecimento do direito.','Pagamento extingue a obrigação e, no âmbito federal, ocorre via mecanismos do SIAFI.'],daily:'NF está correta, mas há divergência entre período faturado e evidência da prestação.',chief:'Suspenda a conclusão da liquidação até esclarecer a divergência, articule correção e preserve evidências.',ask:'O que você confere antes de reconhecer uma despesa como liquidada?',trap:'Confundir emissão da NF com liquidação automática.',memo:['NF ≠ liquidação','Ateste + evidência','Pagamento depois']},
'Retenções tributárias':{ess:['Retenções dependem da natureza do pagamento, do fornecedor e da legislação aplicável.','A análise deve ocorrer antes do pagamento e ficar documentada.','Classificação equivocada pode gerar recolhimento indevido ou omissão.'],daily:'Fornecedor apresenta declaração de regime tributário e a equipe tem dúvida sobre as retenções da NF.',chief:'Confirme natureza do objeto, enquadramento e documentação; consulte regra vigente e evite aplicar alíquota por hábito.',ask:'Como reduzir riscos nas retenções tributárias?',trap:'Decorar uma alíquota e aplicá-la a todo fornecedor.',memo:['Natureza','Regime/documentos','Regra vigente','Evidência']},
'Suprimento, GRU e regularidade fiscal':{ess:['Suprimento de fundos é regime excepcional e exige finalidade e prestação de contas.','GRU/PagTesouro são instrumentos de recolhimento à Conta Única conforme regras do Tesouro.','Regularidade fiscal deve ser verificada no momento e extensão exigidos pela contratação/pagamento.'],daily:'Há necessidade urgente de pequena despesa e alguém sugere suprimento como solução automática.',chief:'Verifique hipótese, excepcionalidade, limites e controles; escolha o instrumento correto e garanta prestação de contas.',ask:'Quando uma solução operacional rápida pode se tornar risco de controle?',trap:'Tratar suprimento de fundos como alternativa comum ao processo de contratação.',memo:['Excepcionalidade','Finalidade','Prestação de contas','Regularidade']},
'Resiliência e flexibilidade':{ess:['Resiliência é manter capacidade decisória sob pressão.','Flexibilidade é adaptar meio e prioridade sem abandonar norma e objetivo.','Chefia deve estabilizar a equipe em momentos críticos.'],daily:'No fechamento, sistema oscila, demandas acumulam e duas pessoas da equipe estão ausentes.',chief:'Repriorize, redistribua, comunique riscos, registre contingências e preserve controles essenciais.',ask:'Conte como reagiria a uma mudança crítica de cenário.',trap:'Confundir flexibilidade com ignorar procedimento.',memo:['Adaptar sem improvisar','Priorizar','Comunicar risco']},
'Articulação entre áreas':{ess:['Processos financeiros atravessam várias unidades.','A chefia precisa definir responsabilidades, prazos e pontos de passagem.','Articulação eficaz reduz devoluções e conflitos.'],daily:'Área demandante, fiscalização contratual e SGOF discordam sobre quem deve sanar uma pendência.',chief:'Delimite competências, reúna evidências, atribua responsáveis e prazo e acompanhe até a solução.',ask:'Como evitar que um processo fique “pingando” entre setores?',trap:'Assumir no SGOF tarefas que pertencem a outra unidade apenas para ganhar velocidade.',memo:['Competência','Responsável','Prazo','Acompanhamento']},
'Comunicação e síntese':studyLessons['Comunicação e síntese']||{ess:['Comunicação gerencial deve ser clara e orientada à decisão.'],daily:'A direção pede posição rápida.',chief:'Informe situação, causa, impacto, ação e próximo passo.',ask:'Resuma um problema complexo em dois minutos.',trap:'Excesso de detalhes sem conclusão.',memo:['Situação','Causa','Impacto','Ação']},
'Norma SEI nº 2/2022/DGP-EBSERH':{ess:['Integra o conjunto institucional de normas de provimento/seleção de funções de confiança da HU Brasil.','Deve ser estudada junto às alterações posteriores e ao POP aplicável, evitando leitura isolada.','Na seleção, interessa compreender requisitos, responsabilidades e fluxo institucional aplicável.'],daily:'Surge dúvida sobre requisito para designação de chefia e alguém usa uma versão antiga da regra.',chief:'Confirme a versão vigente, alterações e POP relacionado antes de orientar a unidade.',ask:'Como você garante aderência normativa em processos de gestão de pessoas ligados à chefia?',trap:'Estudar a norma original ignorando alterações posteriores.',memo:['Versão vigente','Alterações','POP relacionado']},
'Norma SEI nº 5/2025/DGP-EBSERH':{ess:['É alteração posterior no conjunto normativo de provimento e deve ser lida em conjunto com a Norma nº 2/2022.','Em prova/entrevista, a preocupação central é demonstrar uso da regra vigente.','Mudança normativa exige atualização de procedimentos internos.'],daily:'Checklist interno continua reproduzindo requisito anterior à atualização normativa.',chief:'Compare a versão vigente, corrija o checklist e comunique a mudança para evitar decisões inconsistentes.',ask:'Como implementaria uma alteração normativa no setor?',trap:'Conhecer a mudança, mas não atualizar controles e rotinas.',memo:['Norma vigente','Atualizar procedimento','Comunicar equipe']},
'POP.DGP.084 — seleção e nomeação de chefias':{ess:['O POP organiza operacionalmente o processo de seleção/nomeação de funções e cargos de chefia.','POP transforma regra institucional em fluxo executável.','É importante diferenciar requisito normativo de etapa operacional.'],daily:'Uma seleção está correta no mérito, mas uma etapa documental do fluxo não foi cumprida.',chief:'Identifique a etapa, regularize conforme o procedimento e evite avançar sem a evidência necessária.',ask:'Qual a importância de POPs para governança?',trap:'Tratar POP como documento sem impacto no controle.',memo:['Norma = regra','POP = fluxo','Evidência = controle']},
'Valores':{ess:['Valores orientam comportamento e decisões, especialmente quando há pressão por resultado.','Ética, integridade e transparência aparecem no mapa estratégico da Rede.','A chefia demonstra valores pela forma como decide, comunica e controla.'],daily:'Uma área pede tratamento excepcional sem fundamento porque o fornecedor é estratégico.',chief:'Mantenha impessoalidade, transparência e fundamentação, buscando solução regular.',ask:'Como valores institucionais aparecem numa decisão financeira?',trap:'Recitar valores sem exemplo concreto.',memo:['Ética','Integridade','Transparência','Imparcialidade']},
'Direcionadores':{ess:['Direcionadores estratégicos conectam propósito, visão e objetivos.','O mapa 2024–2028 organiza objetivos em cinco pilares.','A chefia deve traduzir estratégia em prioridades do setor.'],daily:'Você precisa escolher entre automatizar controle interno ou manter rotina manual que consome horas da equipe.',chief:'Avalie risco, eficiência e contribuição aos objetivos institucionais, definindo indicador de resultado.',ask:'Como transforma estratégia em ação no SGOF?',trap:'Tratar planejamento estratégico como atividade exclusiva da alta gestão.',memo:['Estratégia → prioridade','Prioridade → ação','Ação → indicador']},
'Objetivos estratégicos':{ess:['O mapa 2024–2028 reúne 24 objetivos estratégicos.','No pilar Sustentabilidade Financeira estão objetivos ligados à eficiência da gestão, financiamento e compras/contratações.','SGOF contribui por qualidade da execução, informação e controle.'],daily:'Execução baixa ameaça uma entrega institucional planejada.',chief:'Identifique causa, proponha correção, monitore indicador e reporte impacto estratégico.',ask:'Qual objetivo estratégico você relacionaria ao trabalho do SGOF e por quê?',trap:'Responder apenas com atividade operacional, sem efeito institucional.',memo:['24 objetivos','Sustentabilidade financeira','Eficiência','Compras/contratações']},
'Governança e visão sistêmica':{ess:['Governança direciona, monitora e avalia a atuação institucional.','Visão sistêmica considera efeitos da decisão financeira sobre assistência, ensino, pesquisa, contratos e pessoas.','Controle deve apoiar resultados sustentáveis.'],daily:'Cortar ou postergar uma despesa melhora o caixa imediato, mas pode comprometer serviço assistencial crítico.',chief:'Avalie impacto transversal, risco, alternativas e escalonamento; apresente decisão com visão institucional.',ask:'Dê exemplo de decisão em que visão sistêmica muda a resposta do SGOF.',trap:'Otimizar apenas o indicador financeiro do setor.',memo:['Direcionar','Monitorar','Avaliar','Impacto transversal']}
});
const questions=[
 ['Qual é a pontuação máxima da 1ª fase?',['20','22','25','30'],'B','O edital fixa 22 pontos para a análise curricular.'],
 ['Na 3ª fase, qual é o aproveitamento mínimo exigido?',['60%','70%','75%','80%'],'D','A 3ª fase exige no mínimo 80% do total de pontos.'],
 ['Qual critério vale até 40 pontos na 2ª fase?',['Formação acadêmica','Negociação, conflitos, decisão, visão sistêmica e articulação','Tempo de HU-UFCAT','Cursos de liderança'],'B','Esse bloco de competências comportamentais e gerenciais vale até 40 pontos.'],
 ['Quanto vale domínio da legislação/literatura da área na 3ª fase?',['10','20','30','40'],'D','É o item de maior peso da 3ª fase: até 40 pontos.'],
 ['Qual o tempo máximo de resposta por questão na entrevista da 2ª fase?',['2 min','3 min','5 min','10 min'],'C','O edital limita cada resposta a cinco minutos.'],
 ['Para Chefia de Setor, qual alternativa atende um dos critérios adicionais?',['6 meses de experiência','2 anos de experiência correlata','Ensino médio','20h de liderança'],'B','Um dos caminhos é possuir pelo menos dois anos de experiência profissional correlata.'],
 ['Qual carga mínima acumulada de gestão de pessoas/liderança é exigida?',['20h','30h','40h','60h'],'C','São 40 horas acumuladas, comprováveis até o exercício da função se selecionado.'],
 ['Na 3ª fase, Mapa Estratégico vale até quantos pontos?',['10','15','20','30'],'C','Direcionadores, propósito, visão, valores e objetivos estratégicos valem até 20 pontos.']
];
questions.push(
 ['Qual é a diferença central entre crédito e recurso?',['Crédito é dinheiro; recurso é autorização','São sinônimos','Crédito é autorização orçamentária; recurso é disponibilidade financeira','Crédito existe apenas após pagamento'],'C','Crédito está no enfoque orçamentário; recurso, no financeiro.'],
 ['Restos a Pagar processados são despesas:',['Empenhadas e já liquidadas, ainda não pagas','Apenas previstas na LOA','Pagas sem empenho','Não empenhadas'],'A','Processados já passaram pela liquidação.'],
 ['A emissão da nota fiscal, sozinha:',['Liquida automaticamente','Substitui o ateste','Não basta para liquidar; é preciso verificar o direito do credor','Autoriza o pagamento'],'C','A liquidação exige verificação do direito adquirido e documentação pertinente.'],
 ['Na gestão de conflito técnico, a melhor primeira abordagem é:',['Escolher a área hierarquicamente superior','Ignorar para cumprir prazo','Delimitar a divergência, reunir fatos e norma e ouvir as áreas','Transferir a decisão'],'C','A chefia precisa compreender o conflito antes de decidir fundamentadamente.'],
 ['O Tesouro Gerencial é especialmente útil para:',['Assinar contratos','Gerar consultas e análises gerenciais','Substituir a LOA','Nomear chefias'],'B','É ferramenta de consulta gerencial baseada em informações do SIAFI e outros sistemas.'],
 ['Qual sequência representa melhor a despesa pública?',['Pagamento → empenho → liquidação','Liquidação → empenho → pagamento','Empenho → liquidação → pagamento','Empenho → pagamento → liquidação'],'C','Os três estágios são empenho, liquidação e pagamento.'],
 ['Em uma resposta de chefia sobre problema complexo, é mais forte:',['Citar muitas normas sem decidir','Diagnosticar, avaliar risco, decidir, articular e monitorar','Dizer que consultaria a chefia superior','Prometer resolver sozinho'],'B','A banca avalia decisão, visão sistêmica, articulação, conformidade e síntese.'],
 ['No Mapa Estratégico 2024–2028, Sustentabilidade Financeira inclui:',['Somente ensino','Eficiência, financiamento e compras/contratações','Somente assistência','Apenas gestão de pessoas'],'B','O pilar inclui objetivos de eficiência, fontes de financiamento e aprimoramento de compras e contratações.'],
 ['Uma equipe dependente de uma única pessoa para rotina crítica apresenta principalmente:',['Eficiência máxima','Risco de continuidade e conhecimento','Segregação perfeita','Excesso de governança'],'B','A chefia deve reduzir pontos únicos de conhecimento.'],
 ['Flexibilidade gerencial significa:',['Ignorar norma em emergência','Adaptar meios e prioridades preservando controles e objetivo','Mudar decisão a cada pressão','Delegar toda decisão'],'B','Flexibilidade não equivale a abandonar conformidade.'],
 ['A disponibilidade orçamentária:',['É o pagamento','É controle prévio sobre suporte orçamentário','Substitui o empenho','É sempre recurso financeiro'],'B','Ela ajuda a verificar suporte antes da assunção da obrigação.'],
 ['Uma baixa execução deve ser analisada primeiro por:',['Opinião da equipe','Planejado x realizado e estágio/gargalos da despesa','Número de servidores apenas','Valor pago apenas'],'B','O diagnóstico precisa localizar onde a execução está travando.']
);
const cases=[
 ['Fornecedor essencial está com pendência de regularidade e a área pressiona pelo pagamento. Como conduzir?','Verifique a exigência aplicável e a pendência, dimensione risco e impacto assistencial, articule regularização com fornecedor/gestor contratual, documente e acompanhe. Não transforme urgência em dispensa automática de controle.'],
 ['Contabilidade e SGOF divergem sobre procedimento de liquidação. Como decidir?','Delimite a divergência, reúna documentos e norma, ouça as áreas, defina competência e risco, adote entendimento fundamentado e registre/padronize a solução.'],
 ['Fechamento do exercício: grande volume de empenhos e risco de prazo. Como organizar?','Mapeie carteira, classifique por prazo/risco/impacto, distribua responsáveis, faça checkpoints, trate pendências com as áreas e acompanhe RAP e saldos diariamente.'],
 ['Execução orçamentária abaixo do planejado. O que apresentar à Diretoria?','Compare planejado x realizado, segmente por objeto/unidade/estágio, identifique causas, impacto e valores, proponha ações com responsável/prazo e crie monitoramento.'],
 ['Servidor experiente resiste a novo controle. Como gerenciar?','Escute a causa, explique risco e objetivo, envolva-o na solução quando possível, capacite, defina expectativa e acompanhe adesão sem abrir mão do controle necessário.'],
 ['Nota fiscal chega sem ateste, mas o serviço é crítico e o vencimento é hoje.','Não reconheça liquidação sem evidência. Acione imediatamente fiscalização/área competente, registre a pendência, avalie consequências e acompanhe regularização para pagamento tempestivo quando possível.'],
 ['Há dotação, mas falta recurso financeiro imediato para pagar todas as obrigações.','Diferencie crédito de recurso, levante obrigações e vencimentos, priorize segundo critérios institucionais/normativos, articule programação financeira e comunique riscos.'],
 ['No fim do ano existem empenhos sem entrega e outros já liquidados. Como tratar?','Separe processados e não processados, valide condições de inscrição/manutenção em RAP e evite carregar saldos sem obrigação/justificativa.'],
 ['A direção pede uma apresentação de 3 minutos sobre atraso em pagamentos.','Estruture: situação atual, valor/escopo afetado, causa, risco, providência, dependência e próximo marco. Leve detalhes como apoio, mas não comece por eles.'],
 ['Um erro de classificação no empenho só é percebido na liquidação.','Interrompa a propagação do erro, identifique causa e regularização cabível, corrija na origem e transforme o caso em melhoria preventiva.'],
 ['Duas áreas devolvem o mesmo processo uma para a outra e o prazo está vencendo.','Defina a pendência objetiva, competência de cada área, responsável e prazo; articule solução conjunta e registre entendimento para evitar recorrência.'],
 ['Uma pequena despesa urgente é proposta para suprimento de fundos apenas para ganhar velocidade.','Verifique se a hipótese é realmente compatível com o regime excepcional, limites e controles. Urgência isolada não deve substituir o processo adequado.']
];
const phase1=[
 ['Experiência específica na área da função','1 ponto por ano • máximo 8','Separe certidões/declarações com período e atividades claramente descritas.'],
 ['Experiência profissional correlata','0,5 ponto por ano • máximo 6','Demonstre a correlação das atividades com orçamento, finanças, contabilidade, gestão ou processos afins.'],
 ['Exercício de função gerencial','1 ponto por ano • máximo 4','Evidencie formalmente período, unidade e responsabilidade gerencial.'],
 ['Capacitação específica','0,5 ponto a cada 15h • máximo 3','Priorize certificados diretamente ligados à função.'],
 ['Capacitação correlata','0,5 ponto a cada 10h • máximo 1','Organize cursos complementares e carga horária comprovável.']
];
const phase2Rubric=[
 ['Decisão, conflitos, visão sistêmica, conformidade e articulação',40,'Responda com problema → risco/norma → alternativas → decisão → articulação → controle.'],
 ['Resiliência, flexibilidade, equipe e relacionamento',30,'Mostre adaptação sem perda de controle, comunicação e desenvolvimento da equipe.'],
 ['Argumentação, organização, clareza e síntese',20,'Abra com a tese, use poucos blocos e conclua com resultado/próximo passo.'],
 ['Habilidade técnica',15,'Use conceitos corretos e conecte-os ao cotidiano do SGOF.']
];
const phase3Plan=[
 ['Legislação/literatura técnica',40,'Lei 4.320, execução, empenho, liquidação, pagamento, RAP, controles e normativos da área.'],
 ['Administração Pública / HU Brasil',30,'Princípios, governança, integridade e normativos institucionais aplicáveis.'],
 ['Mapa Estratégico',20,'Propósito, visão, valores, pilares, objetivos e contribuição do SGOF.'],
 ['Sistemas e rotina',10,'SIAFI, Tesouro Gerencial e capacidade de interpretar a execução.']
];
const interview=[
 ['Conte sua trajetória e explique por que está preparado para chefiar o SGOF.','Estruture em: experiência → domínio técnico → liderança → contribuição ao HU-UFCAT.'],
 ['Como você gerencia conflitos entre áreas?','Mostre escuta, fatos/normas, construção de solução, decisão e acompanhamento.'],
 ['Como garantir conformidade sem travar a execução?','Fale em planejamento, checklist, orientação prévia, segregação de funções, controles e gestão de risco.'],
 ['Como você lideraria a equipe do SGOF?','Metas claras, distribuição por competência, comunicação, acompanhamento, desenvolvimento e responsabilização.'],
 ['Qual sua visão sobre o papel do SGOF no hospital?','Conecte orçamento/finanças à continuidade assistencial, legalidade, eficiência e estratégia institucional.']
];

export default function App(){
 const [page,setPage]=useState('painel'),[done,setDone]=useState(()=>JSON.parse(localStorage.getItem('sgofDone')||'{}')),[qi,setQi]=useState(0),[choice,setChoice]=useState(''),[result,setResult]=useState(null),[score,setScore]=useState(()=>+localStorage.getItem('sgofScore')||0),[attempts,setAttempts]=useState(()=>+localStorage.getItem('sgofAttempts')||0),[caseI,setCaseI]=useState(0),[lesson,setLesson]=useState(null);
 const total=modules.reduce((n,m)=>n+m.topics.length,0), completed=Object.values(done).filter(Boolean).length, mastery=Math.round(completed/total*100);
 const toggle=t=>{const n={...done,[t]:!done[t]};setDone(n);localStorage.setItem('sgofDone',JSON.stringify(n))};
 const answer=()=>{if(!choice)return;const ok=choice===questions[qi][2];setResult(ok);const a=attempts+1,s=score+(ok?1:0);setAttempts(a);setScore(s);localStorage.setItem('sgofAttempts',a);localStorage.setItem('sgofScore',s)};
 const next=()=>{setQi((qi+1)%questions.length);setChoice('');setResult(null)};
 const pct=attempts?Math.round(score/attempts*100):0;
 const nav=[['painel','Painel',LayoutDashboard],['fase1','Fase 1 • Currículo',ClipboardCheck],['trilha','Trilha de estudo',BookOpen],['questoes','Questões',Brain],['entrevista','Fase 2 • Entrevista',Users],['casos','Casos práticos',ClipboardCheck],['fase3','Fase 3 • 80%+',Target]];
 return <main className="shell"><aside><div className="brand"><b>SGOF</b><span>Preparação para Chefia</span></div><nav>{nav.map(([id,l,I])=><button className={page===id?'active':''} onClick={()=>setPage(id)}><I size={18}/>{l}</button>)}</nav><div className="progressBox"><small>Trilha concluída</small><strong>{mastery}%</strong><div><i style={{width:mastery+'%'}}/></div></div></aside><section className="content">
 {page==='painel'&&<><Header/><div className="stats"><Card icon={Trophy} label="Meta 3ª fase" value="80%"/><Card icon={CheckCircle2} label="Tópicos estudados" value={completed+'/'+total}/><Card icon={Brain} label="Questões" value={attempts}/><Card icon={Target} label="Aproveitamento" value={pct+'%'}/></div><article className="alert"><b>Prioridade máxima: 3ª fase</b><p>Domínio técnico e normativo, Administração Pública/HU Brasil, Mapa Estratégico e sistemas da rotina. Treine para ultrapassar 80% com margem.</p><button onClick={()=>setPage('fase3')}>Começar preparação prioritária</button></article><h2>Plano de ataque</h2><div className="grid"><Mini title="1ª Fase • Currículo" text="Organize comprovações de experiência, gestão e capacitações. Máximo: 22 pontos."/><Mini title="2ª Fase • Entrevista" text="Treine respostas de até 5 minutos: decisão, conflitos, liderança, articulação e técnica."/><Mini title="3ª Fase • Diretoria" text="Barreira de 80%. Foque legislação, estratégia HU Brasil e sistemas/rotinas do SGOF."/></div></>}
 {page==='fase1'&&<><Title tag="1ª FASE • ATÉ 22 PONTOS" title="Currículo estratégico" text="Use esta área como checklist de comprovação. A meta é não perder ponto por documento mal apresentado."/><div className="phaseTable">{phase1.map((x,i)=><article><small>CRITÉRIO {i+1}</small><h3>{x[0]}</h3><strong>{x[1]}</strong><p>{x[2]}</p></article>)}</div><article className="alert"><b>Checklist antes de enviar</b><p>Período legível • vínculo identificado • atividades descritas • carga horária dos cursos • documento oficial/assinável • correlação evidente com a função.</p></article></>}
 {page==='trilha'&&!lesson&&<><Title tag="CONTEÚDO DIRECIONADO" title="Trilha de estudo SGOF" text="Clique nos tópicos destacados para abrir uma microaula aplicada ao cotidiano e à entrevista."/><div className="modules">{modules.map(m=><article><h3>{m.name}</h3>{m.topics.map(t=><div className="topicLine"><input type="checkbox" checked={!!done[t]} onChange={()=>toggle(t)}/><button onClick={()=>studyLessons[t]&&setLesson(t)} disabled={!studyLessons[t]}><span>{t}</span><small>{studyLessons[t]?'Estudar com caso prático →':'Conteúdo em expansão'}</small></button></div>)}</article>)}</div></>}
 {page==='trilha'&&lesson&&<StudyLesson title={lesson} data={studyLessons[lesson]} done={!!done[lesson]} onDone={()=>toggle(lesson)} onBack={()=>setLesson(null)}/>} 
 {page==='questoes'&&<><Title tag="TREINO OBJETIVO" title="Questões do edital" text="Banco inicial baseado diretamente nos critérios do Edital 02/2026."/><Question q={questions[qi]} qi={qi} choice={choice} setChoice={setChoice} result={result} answer={answer} next={next}/></>}
 {page==='entrevista'&&<><Title tag="2ª FASE • ENTREVISTA" title="Simulador de entrevista" text="Treine em voz alta. Cada resposta deve caber em até 5 minutos. Abaixo, estude também exatamente o que a comissão pontua."/><div className="rubric">{phase2Rubric.map(x=><article><strong>{x[1]} pts</strong><h3>{x[0]}</h3><p>{x[2]}</p></article>)}</div><div className="modules">{interview.map((x,i)=><article><small>PERGUNTA {i+1}</small><h3>{x[0]}</h3><p>{x[1]}</p><button onClick={()=>navigator.clipboard?.writeText(x[0])}>Copiar pergunta</button></article>)}</div></>}
 {page==='casos'&&<><Title tag="CHEFIA NA PRÁTICA" title="Casos situacionais" text="Responda como chefe: identifique risco, norma aplicável, decisão, comunicação e controle posterior."/><article className="case"><span>CASO {caseI+1}/{cases.length}</span><h2>{cases[caseI][0]}</h2><div className="framework"><b>Roteiro da resposta</b><p>1. Diagnóstico → 2. Norma/controle → 3. Risco → 4. Decisão → 5. Articulação → 6. Monitoramento.</p></div><details className="caseAnswer"><summary>Conferir resposta-modelo</summary><p>{cases[caseI][1]}</p></details><button onClick={()=>setCaseI((caseI+1)%cases.length)}>Próximo caso</button></article></>}
 {page==='fase3'&&<><Title tag="3ª FASE • ELIMINATÓRIA" title="Rumo aos 80%" text="Sua preparação principal. O objetivo é chegar à entrevista técnica dominando os quatro blocos avaliados."/><div className="weights">{phase3Plan.map(x=><article className="mini"><h3>{x[0]} • {x[1]} pts</h3><p>{x[2]}</p></article>)}</div><article className="framework"><b>Como responder na 3ª fase</b><p>Conceito/norma → aplicação no SGOF → risco se não observar → decisão da chefia → contribuição para o hospital. Evite respostas puramente decoradas.</p></article><article className="alert"><b>Meta de segurança: 90%</b><p>O edital elimina abaixo de 80%. Estude para uma margem superior, priorizando os blocos de 40 e 30 pontos.</p><button onClick={()=>setPage('trilha')}>Abrir trilha de estudo</button></article></>}
 </section></main>
}
function Header(){return <header className="hero"><span>EDITAL Nº 02/2026 • HU-UFCAT</span><h1>Chefia do Setor de Gestão Orçamentária e Financeira</h1><p>Treinamento direcionado para vencer as três fases do processo seletivo.</p></header>}
function Title({tag,title,text}){return <header className="hero small"><span>{tag}</span><h1>{title}</h1><p>{text}</p></header>}
function Card({icon:I,label,value}){return <article className="card"><I/><span>{label}</span><strong>{value}</strong></article>}
function Mini({title,text}){return <article className="mini"><h3>{title}</h3><p>{text}</p></article>}
function Question({q,qi,choice,setChoice,result,answer,next}){return <article className="question"><small>QUESTÃO {qi+1}</small><h2>{q[0]}</h2>{q[1].map((o,i)=>{const l=String.fromCharCode(65+i);return <button disabled={result!==null} className={choice===l?'picked':''} onClick={()=>setChoice(l)}><b>{l}</b>{o}</button>})}{result===null?<button className="primary" onClick={answer}>Corrigir</button>:<div className={result?'feedback ok':'feedback no'}><b>{result?'Resposta correta':'Resposta incorreta — gabarito '+q[2]}</b><p>{q[3]}</p><button onClick={next}>Próxima questão</button></div>}</article>}

function StudyLesson({title,data,done,onDone,onBack}){return <><button className="backBtn" onClick={onBack}>← Voltar à trilha</button><Title tag="MICROAULA APLICADA" title={title} text="Aprenda o ponto essencial, aplique ao cotidiano do SGOF e treine como responder na seleção."/><div className="studyGrid"><article><h3>📘 Pontos essenciais</h3>{data.ess.map(x=><p>• {x}</p>)}</article><article><h3>🏥 Situação cotidiana</h3><p>{data.daily}</p></article><article><h3>👔 Conduta esperada da chefia</h3><p>{data.chief}</p></article><article className="interviewStudy"><h3>🎤 Treine antes de abrir a ideia-chave</h3><h2>{data.ask}</h2><details><summary>Ver roteiro de uma resposta forte</summary><p>Contextualize o problema → identifique risco e fundamento → explique sua decisão → mostre articulação com as áreas → finalize com acompanhamento e resultado esperado.</p></details></article><article className="trapStudy"><h3>⚠️ Pegadinha</h3><p>{data.trap}</p></article><article><h3>🧠 Memorize</h3><div className="memoChips">{data.memo.map(x=><span>{x}</span>)}</div></article></div><button className="doneBtn" onClick={onDone}>{done?'✓ Concluído — marcar para revisar':'Concluir esta microaula'}</button></>}